# Generated by Django 5.2.3 on 2025-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('sport', 'Sport'), ('programing', 'Programing')], default='sport'),
        ),
    ]
