# Generated by Django 5.2.3 on 2025-07-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_categories_article_categories'),
    ]

    operations = [
    ]
