# Generated by Django 5.2.3 on 2025-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('sport', 'Sport'), ('programing', 'Programing'), ('politics', 'Politics'), ('economy', 'Economy'), ('technology', 'Technology'), ('health', 'Health'), ('education', 'Education'), ('art', 'Art'), ('culture', 'Culture'), ('science', 'Science'), ('opinion', 'Opinion'), ('entertainment', 'Entertainment')], default='sport'),
        ),
    ]
